theme: jekyll-theme-cayman
title: [Deep Segmentation]
description: [Automated cartilage segmentation from High-Resolution 3D Steady-State knee MR images using Deep Learning models]
by: ['Joe Arrowsmith, Olivia Gallupova, Joonsu Gha, Lapo Rastrelli, Pietro Vitiello']
