theme: jekyll-theme-cayman
title: [Automated Segmentation of Knee Cartilage]
description: [Automated tissue segmentation from High-Resolution 3D Steady-State knee MR images using Deep Learning architectures]
